### ISSUE TITLE
Missing functions.php file when trying to install

### ISSUE THREAD

**Issue by bensherred** [arusf2011/tachograph#1]
When trying to access the /installer route you get an error saying it can't find a file called functions.php in the /app folder.

Creating an empty file fixed this so you probably just need to remove the require line.

**Comment by arusf2011** [comment]
The error is displayed because index.php contains the line in which he requires that file, but there is no file.
In this case then I'm gonna change that file to check if there is available LOCK file.
If not, then it'll not require this file.
In other cases it'll be required.

**Comment by arusf2011** [comment]
The issue should be fixed.
Please tell me if you can.

**Comment by arusf2011** [comment]
Since there is no comment to this, I'll assume that now everything is working fine.
Closing.
