### ISSUE TITLE
Wrong Image Name

### ISSUE THREAD

**Issue by Wachert** [arusf2011/tachograph#2]
https://github.com/arusf2011/tachograph/blob/8bc536143143c167c4251e79c7c4cb15ac5c2405/app/ui/installer.php#L16

image existing as truck.png not truck_tacho.png

**Comment by arusf2011** [comment]
Investigating.

**Comment by arusf2011** [comment]
Please check if anything is now okay.
If you'll not reply in 7 days, I'll close this issue.

**Comment by arusf2011** [comment]
Since there is no comment to this, I'll assume that now everything is working fine.
Closing.
